### ISSUE TITLE
GPU Support

### ISSUE THREAD

**Issue by rvadaga** [clab/stack-lstm-ner#14]
I could run this code successfully on CPU. But, I want to use GPUs for computation. So, in step 6 of INSTALL.md, I used `-DBACKEND=cuda` to build `nvcc` binaries for `cnn`. It ran successfully, but how do I build `nvcc` binaries from `lstm-parse.cc` using `cmake` in the topmost directory? When I did `make`, it was only generating `CXX` binaries. Is there any option to build `nvcc` binaries?

**Comment by miguelballesteros** [comment]
We never tried on this but I guess it should be possible. I believe this is a question for Dynet developers.
@yoavg or @neubig  might be able to help.

Thanks!

**Comment by neubig** [comment]
Hi @VSRahul , as noted here: http://dynet.readthedocs.io/en/latest/install.html#gpu-cuda-support the only change you need to make when compiling lstm-parse.cc is link to the "libgdynet" and "libdynetcuda" libraries instead of linking to "libdynet" (change "-ldynet" on the command line to the options listed on the linked page).

That being said, GPU probably won't help much for the LSTM parser, and it may even be significantly slower. This is because the parser has a structure that is not easy to mini-batch, and mini-batching is important for getting performance increases on GPU.

**Comment by miguelballesteros** [comment]
Thanks a lot @neubig 

This is the stack-lstm-ner system but it has a very similar structure to the stack-lstm-parser, so what @neubig says it also applies here.
